FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY CountingCars.sln . /
COPY IdentityService/IdentityService.csproj ./IdentityService/

RUN dotnet restore ./IdentityService/IdentityService.csproj

COPY . .
RUN dotnet publish ./IdentityService/IdentityService.csproj -c Release -o /app/publish

# release mode
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT [ "dotnet","IdentityService.dll" ]