FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY CountingCars.sln . /
COPY AuctionService/AuctionService.csproj ./AuctionService/
COPY Contracts/Contracts.csproj ./Contracts/

RUN dotnet restore ./AuctionService/AuctionService.csproj

COPY . .
RUN dotnet publish ./AuctionService/AuctionService.csproj -c Release -o /app/publish

# release mode
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT [ "dotnet","AuctionService.dll" ]